title: Saurabh Harak Portfolio 
description: AI/ML AlchemistğŸ¤– & Data SorcererğŸ“Š with a Full Stack Developer Origin ğŸš€ | Python Developer ğŸ | Full Stack Background ğŸ’»| 4+ Years Experience â±ï¸| Let's dive into the world of data-driven possibilities! ğŸ“ˆğŸ“ŠğŸ’¡

show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
